<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Pottmayer.Tars.Core.Ddd\Pottmayer.Tars.Core.Ddd.csproj" />
    <ProjectReference Include="..\Pottmayer.Tars.Data.Abstractions\Pottmayer.Tars.Data.Abstractions.csproj" />
    <ProjectReference Include="..\Pottmayer.Tars.Data\Pottmayer.Tars.Data.csproj" />
    <ProjectReference Include="..\Pottmayer.Tars.Data.Document.Abstractions\Pottmayer.Tars.Data.Document.Abstractions.csproj" />
    <ProjectReference Include="..\..\Multitenancy\Pottmayer.Tars.Multitenancy.Abstractions\Pottmayer.Tars.Multitenancy.Abstractions.csproj" />
  </ItemGroup>

</Project>
