<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Pottmayer.Tars.Observability.AspNetCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pottmayer.Tars.Observability\Pottmayer.Tars.Observability.csproj" />
    <ProjectReference Include="..\Pottmayer.Tars.Observability.Abstractions\Pottmayer.Tars.Observability.Abstractions.csproj" />
  </ItemGroup>

</Project>
